#pragma once
#include <fullerenes/sycl-headers/tutte-kernel.hh>
#include <fullerenes/sycl-headers/spherical-projection-kernel.hh>
#include <fullerenes/sycl-headers/dualize-kernel.hh>
#include <fullerenes/sycl-headers/sycl-parallel-primitives.hh>
#include <fullerenes/sycl-headers/forcefield-optimize-kernel.hh>
#include <fullerenes/sycl-headers/hessian-kernel.hh>
#include <fullerenes/sycl-headers/eigen-kernels.hh>
#include <fullerenes/sycl-headers/geometry-kernels.hh>