// bindings_generated.cc -- GENERATED by tools/gen_bindings.py. DO NOT EDIT.
// Regenerate with: python3 tools/gen_bindings.py
//
// One register_generated_<PyClass>(cls) per spec'd class, adding the mechanical
// method surface harvested from the clang AST. The hand-written per-class .cc
// creates the py::class_, calls bind_graph_common, then calls these.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "common.hh"
#include "np_interop.hh"

#include "fullerenes/fullerenegraph.hh"
#include "fullerenes/triangulation.hh"
#include "fullerenes/polyhedron.hh"
#include "fullerenes/deltahedron.hh"

namespace py = pybind11;


void register_generated_FullereneGraph(py::class_<pyf::PyGraph<FullereneGraph, FullereneGraphView>>& cls) {
    using W = pyf::PyGraph<FullereneGraph, FullereneGraphView>;
    cls.def("pentagon_distance_mtx", [](W& w) { return pyf::matrix_copy<int>(w.view().pentagon_distance_mtx()); });
    cls.def("is_cubic", [](W& w) { return w.view().is_cubic(); });
    cls.def("is_triangulation", [](W& w) { return w.view().is_triangulation(); });
    cls.def("count_perfect_matchings", [](W& w) { return w.view().count_perfect_matchings(); });
    cls.def("is_consistently_oriented", [](W& w) { return w.view().is_consistently_oriented(); });
    cls.def("adjacency_is_symmetric", [](W& w) { return w.view().adjacency_is_symmetric(); });
    cls.def("has_separating_triangles", [](W& w) { return w.view().has_separating_triangles(); });
    cls.def("max_degree", [](W& w) { return w.view().max_degree(); });
    cls.def("count_edges", [](W& w) { return w.view().count_edges(); });
}

void register_generated_FullereneDual(py::class_<pyf::PyGraph<FullereneDual, FullereneDualView>>& cls) {
    using W = pyf::PyGraph<FullereneDual, FullereneDualView>;
    cls.def("cubic_faces", [](W& w) { return pyf::faces_copy(w.view().cubic_faces()); });
    cls.def("max_degree", [](W& w) { return w.view().max_degree(); });
    cls.def("compute_faces_oriented", [](W& w) { return pyf::tris_copy(w.view().compute_faces_oriented()); });
    cls.def("triangles", [](W& w) { return pyf::tris_copy(w.view().triangles()); });
    cls.def("n_triangles", [](W& w) { return w.view().n_triangles(); });
    cls.def("pentagon_distance_mtx", [](W& w) { return pyf::matrix_copy<int>(w.view().pentagon_distance_mtx()); });
    cls.def("is_cubic", [](W& w) { return w.view().is_cubic(); });
    cls.def("is_triangulation", [](W& w) { return w.view().is_triangulation(); });
    cls.def("count_perfect_matchings", [](W& w) { return w.view().count_perfect_matchings(); });
    cls.def("is_consistently_oriented", [](W& w) { return w.view().is_consistently_oriented(); });
    cls.def("adjacency_is_symmetric", [](W& w) { return w.view().adjacency_is_symmetric(); });
    cls.def("has_separating_triangles", [](W& w) { return w.view().has_separating_triangles(); });
    cls.def("count_edges", [](W& w) { return w.view().count_edges(); });
}

void register_generated_Polyhedron(py::class_<pyf::PyGeom<Polyhedron, PolyhedronView<double>>>& cls) {
    using W = pyf::PyGeom<Polyhedron, PolyhedronView<double>>;
    cls.def("surface_area", [](W& w) { return w.view().surface_area(); });
    cls.def("volume", [](W& w) { return w.view().volume(); });
    cls.def("volume_tetra", [](W& w) { return w.view().volume_tetra(); });
    cls.def("volume_divergence", [](W& w) { return w.view().volume_divergence(); });
    cls.def("diameter", [](W& w) { return w.view().diameter(); });
    cls.def("width_height_depth", [](W& w) { return pyf::coord3d_copy(w.view().width_height_depth()); });
    cls.def("inertia_matrix", [](W& w) { return pyf::matrix3d_copy(w.view().inertia_matrix()); });
    cls.def("principal_axes", [](W& w) { return pyf::matrix3d_copy(w.view().principal_axes()); });
    cls.def("is_invalid", [](W& w) { return w.view().is_invalid(); });
    cls.def("is_cubic", [](W& w) { return w.view().is_cubic(); });
    cls.def("is_triangulation", [](W& w) { return w.view().is_triangulation(); });
    cls.def("count_perfect_matchings", [](W& w) { return w.view().count_perfect_matchings(); });
    cls.def("is_consistently_oriented", [](W& w) { return w.view().is_consistently_oriented(); });
    cls.def("adjacency_is_symmetric", [](W& w) { return w.view().adjacency_is_symmetric(); });
    cls.def("has_separating_triangles", [](W& w) { return w.view().has_separating_triangles(); });
    cls.def("max_degree", [](W& w) { return w.view().max_degree(); });
    cls.def("count_edges", [](W& w) { return w.view().count_edges(); });
}

void register_generated_Deltahedron(py::class_<pyf::PyGeom<Deltahedron, DeltahedronView<double>>>& cls) {
    using W = pyf::PyGeom<Deltahedron, DeltahedronView<double>>;
    cls.def("max_angle_relerr", [](W& w) { return w.view().max_angle_relerr(); });
    cls.def("count_concave", [](W& w) { return w.view().count_concave(); });
    cls.def("compute_dual_faces", [](W& w) { return pyf::faces_copy(w.view().compute_dual_faces()); });
    cls.def("cubic_faces", [](W& w) { return pyf::faces_copy(w.view().cubic_faces()); });
    cls.def("max_degree", [](W& w) { return w.view().max_degree(); });
    cls.def("compute_faces_oriented", [](W& w) { return pyf::tris_copy(w.view().compute_faces_oriented()); });
    cls.def("triangles", [](W& w) { return pyf::tris_copy(w.view().triangles()); });
    cls.def("n_triangles", [](W& w) { return w.view().n_triangles(); });
    cls.def("pentagon_distance_mtx", [](W& w) { return pyf::matrix_copy<int>(w.view().pentagon_distance_mtx()); });
    cls.def("is_cubic", [](W& w) { return w.view().is_cubic(); });
    cls.def("is_triangulation", [](W& w) { return w.view().is_triangulation(); });
    cls.def("count_perfect_matchings", [](W& w) { return w.view().count_perfect_matchings(); });
    cls.def("is_consistently_oriented", [](W& w) { return w.view().is_consistently_oriented(); });
    cls.def("adjacency_is_symmetric", [](W& w) { return w.view().adjacency_is_symmetric(); });
    cls.def("has_separating_triangles", [](W& w) { return w.view().has_separating_triangles(); });
    cls.def("count_edges", [](W& w) { return w.view().count_edges(); });
}
