#pragma once

#include <vector>
#include <numeric>
#include <utility>

// Disjoint-set forest (union-find) with path compression and union by size.
// Near-constant amortised cost (inverse-Ackermann) per find/unite.
//
// Used wherever the codebase needs connected components / orbit partitions
// (e.g. Symmetry::equivalence_classes) so the algorithm lives in one named
// place rather than being re-inlined per call site.
class UnionFind {
  std::vector<int> parent_, size_;

public:
  explicit UnionFind(int n) : parent_(n), size_(n, 1) {
    std::iota(parent_.begin(), parent_.end(), 0);
  }

  int n() const { return (int)parent_.size(); }

  // Representative of x's set, with path compression.
  int find(int x) {
    while (parent_[x] != x) { parent_[x] = parent_[parent_[x]]; x = parent_[x]; }
    return x;
  }

  // Merge the sets containing a and b. Returns true if they were distinct.
  bool unite(int a, int b) {
    a = find(a); b = find(b);
    if (a == b) return false;
    if (size_[a] < size_[b]) std::swap(a, b);   // attach smaller under larger
    parent_[b] = a;
    size_[a] += size_[b];
    return true;
  }

  bool connected(int a, int b) { return find(a) == find(b); }

  // @anchor union-find-components
  // @post partition: result is the partition of {0..n-1} by find-equivalence --
  //                  u and v share a class iff find(u) == find(v). Members are
  //                  ascending; classes appear in order of their smallest member.
  // @time O(n * alpha(n))
  std::vector<std::vector<int>> components() {
    std::vector<int> slot(parent_.size(), -1);
    std::vector<std::vector<int>> comps;
    for (int u = 0; u < n(); ++u) {
      int r = find(u);
      if (slot[r] < 0) { slot[r] = (int)comps.size(); comps.push_back({}); }
      comps[slot[r]].push_back(u);
    }
    return comps;
  }
};

// Orbit partition of {0..n-1} under the group generated by G. Each pi need only
// be indexable as pi[u] for u in [0,n), so this serves both vector<Permutation>
// and vector<vector<int>> callers.
//
// @anchor orbits-of-group
// @pre  n_nonneg: n >= 0
// @pre  in_range: every pi in G maps {0..n-1} into itself (pi[u] in [0,n) for u in [0,n))
// @post partition: result is a partition of {0..n-1} into the orbits of <G> --
//                  u and v share a class iff they are connected by the relation
//                  u ~ pi[u] over the pi in G (its connected components).
// @time  O(n * |G| * alpha(n))
// @space O(n)
template<class Perm>
std::vector<std::vector<int>> orbits(int n, const std::vector<Perm>& G) {
  UnionFind uf(n);
  for (const auto& pi : G)
    for (int u = 0; u < n; ++u) uf.unite(u, pi[u]);
  return uf.components();
}
