#pragma once
#include <fullerenes/kernel-headers/tutte.hh>
#include <fullerenes/kernel-headers/spherical-projection.hh>
#include <fullerenes/kernel-headers/dualize.hh>
#include <fullerenes/kernel-headers/sycl-parallel-primitives.hh>
#include <fullerenes/kernel-headers/forcefield-optimize.hh>
#include <fullerenes/kernel-headers/hessian.hh>
#include <fullerenes/kernel-headers/eigen.hh>
#include <fullerenes/kernel-headers/geometry.hh>